# Generated by Django 4.0.5 on 2022-06-03 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imge_caption',
            new_name='name',
        ),
    ]
