# Generated by Django 4.0.5 on 2022-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0004_rename_img_name_image_caption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='imge_caption',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
