# Generated by Django 4.0.5 on 2022-06-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0005_rename_caption_image_imge_caption_remove_image_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='name',
        ),
    ]
