# Generated by Django 4.0.5 on 2022-06-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapp', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='image',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
