# Generated by Django 4.0.5 on 2022-06-06 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instapp', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likess',
            field=models.ManyToManyField(related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
